artifacts_root: artifacts


# ------------------------------------------ Data_Ingestion ------------------------------------ 


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/SubramanyaNayak-github/Datasets/raw/main/boston_dataset.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



# ------------------------------------------ Data_Validation ------------------------------------ 


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/boston_dataset.csv
  status_file: artifacts/data_validation/status.txt


  # ------------------------------------------ Data_Transformation ------------------------------------ 



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/boston_dataset.csv